[project]
name = "geo-gp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.5",
    "pandas>=3.0.1",
    "pyyaml>=6.0.3",
    "scipy>=1.16.3",
    "torch>=2.9.1",
]
